steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/ctx-airules-server:latest", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/ctx-airules-server:latest"]
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args:
  - "run"
  - "deploy"
  - "ctx-airules-server"
  - "--image=gcr.io/$PROJECT_ID/ctx-airules-server:latest"
  - "--platform=managed"
  - "--region=us-central1"
  - "--allow-unauthenticated"
images:
- "gcr.io/$PROJECT_ID/ctx-airules-server:latest"

